apiVersion: apps/v1beta1
kind: Deployment
metadata:   
 name: webapp-deployment1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-deployment1
    spec:
      containers:
        - image: "mansigandhi003/app:latest"
          imagePullPolicy: Always
          name: webapp-deployment1
          ports:
            - containerPort: 3000