apiVersion: apps/v1beta1
kind: Deployment
metadata:   
 name: bff-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bff-deployment
    spec:
      containers:
        - image: "mansigandhi003/bff:latest"
          imagePullPolicy: Always
          name: bff-deployment
          ports:
            - containerPort: 8000