apiVersion: apps/v1beta1
kind: Deployment
metadata:   
 name: historic-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: historic-deployment
    spec:
      containers:
        - image: "mansigandhi003/historic:latest"
          imagePullPolicy: Always
          name: historic-deployment
          ports:
            - containerPort: 8083