apiVersion: apps/v1beta1
kind: Deployment
metadata:   
 name: currency-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: currency-deployment
    spec:
      containers:
        - image: "mansigandhi003/currencyconv:latest"
          imagePullPolicy: Always
          name: currency-deployment
          ports:
            - containerPort: 8081